final modelData = {
  "chat": [
    {
      "provider": "openai",
      "models": [
        {
          "id": "gpt-5.3-chat-latest",
          "name": "GPT 5.3 Instant",
          "description": "OpenAI's latest chat-optimized LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "gpt-5.4",
          "name": "GPT 5.4 Instant",
          "description": "OpenAI's latest and greatest LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "gpt-5.4-mini",
          "name": "GPT 5.4 Mini",
          "description": "OpenAI's small GPT 5.4 model",
          "pro": false,
          "new": true,
        },
        {
          "id": "gpt-5.4-nano",
          "name": "GPT 5.4 Nano",
          "description": "OpenAI's smallest GPT 5.4 model",
          "pro": false,
          "new": true,
        },
        {
          "id": "gpt-5.4-thinking",
          "name": "GPT 5.4 Thinking",
          "description": "OpenAI's latest and greatest reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "gpt-5.4-thinking-xhigh",
          "name": "GPT 5.4 Thinking XHigh",
          "description": "OpenAI's latest and greatest reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "gpt-5.3-codex",
          "name": "GPT 5.3 Codex",
          "description": "OpenAI's latest advanced coding LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "gpt-oss-20",
          "name": "GPT OSS 20B",
          "description": "OpenAI's small OSS LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "gpt5-nano",
          "name": "GPT 5 Nano",
          "description": "OpenAI's smallest flagship LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "gpt-oss-120",
          "name": "GPT OSS 120B",
          "description": "OpenAI's advanced OSS LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-4.1-nano",
          "name": "GPT 4.1 Nano",
          "description": "OpenAI's smallest LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "gpt-4.1-mini",
          "name": "GPT 4.1 Mini",
          "description": "OpenAI's small LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-4.1",
          "name": "GPT 4.1",
          "description": "OpenAI's LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.1",
          "name": "GPT 5.1 Instant",
          "description": "OpenAI's fast and smart LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.1-thinking",
          "name": "GPT 5.1 Thinking",
          "description": "OpenAI's recent and smart reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.2",
          "name": "GPT 5.2 Instant",
          "description": "OpenAI's latest and greatest LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.2-thinking",
          "name": "GPT 5.2 Thinking",
          "description": "OpenAI's latest and greatest reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.2-thinking-xhigh",
          "name": "GPT 5.2 Thinking XHigh",
          "description": "OpenAI's latest and greatest reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt5-mini",
          "name": "GPT 5 Mini",
          "description": "OpenAI's small flagship LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt5",
          "name": "GPT 5",
          "description": "OpenAI's flagship LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "o4-mini",
          "name": "o4 mini",
          "description": "OpenAI's recent mini reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "o3",
          "name": "o3",
          "description": "OpenAI's advanced LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt5-medium",
          "name": "GPT 5 Medium",
          "description": "OpenAI's latest flagship reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.1-codex",
          "name": "GPT 5.1 Codex",
          "description": "OpenAI's advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.1-codex-mini",
          "name": "GPT 5.1 Codex Mini",
          "description": "OpenAI's advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.1-codex-max",
          "name": "GPT 5.1 Codex Max",
          "description": "OpenAI's advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt-5.2-codex",
          "name": "GPT 5.2 Codex",
          "description": "OpenAI's latest advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "gpt5-codex",
          "name": "GPT 5 Codex",
          "description": "OpenAI's advanced coding LLM",
          "pro": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "anthropic",
      "models": [
        {
          "id": "anthropic-sonnet-4.6",
          "name": "Claude Sonnet 4.6",
          "description": "Anthropic's latest Sonnet LLM",
          "pro": false,
          "max": true,
          "new": true,
        },
        {
          "id": "anthropic-sonnet-4.6-think",
          "name": "Claude Sonnet 4.6 Thinking",
          "description": "Anthropic's latest Sonnet LLM with thinking",
          "pro": false,
          "max": true,
          "new": true,
        },
        {
          "id": "anthropic-opus-4.6",
          "name": "Claude 4.6 Opus",
          "description": "Anthropic's most advanced LLM",
          "pro": false,
          "max": true,
          "new": true,
        },
        {
          "id": "anthropic-opus-4.6-think",
          "name": "Claude 4.6 Opus Thinking",
          "description": "Anthropic's most advanced LLM with thinking",
          "pro": false,
          "max": true,
          "new": true,
        },
        {
          "id": "anthropic-small",
          "name": "Claude Haiku 4.5",
          "description": "Anthropic's fast and efficient LLM",
          "pro": true,
          "max": false,
          "new": false,
        },
        {
          "id": "anthropic",
          "name": "Claude Sonnet 4.5",
          "description": "Anthropic's latest and greatest LLM",
          "pro": false,
          "max": true,
          "new": false,
        },
        {
          "id": "anthropic-think",
          "name": "Claude Sonnet 4.5 Thinking",
          "description": "Anthropic's latest and greatest LLM with thinking",
          "pro": false,
          "max": true,
          "new": false,
        },
        {
          "id": "anthropic-opus",
          "name": "Claude 4.5 Opus",
          "description": "Anthropic's previous advanced LLM",
          "pro": false,
          "max": true,
          "new": false,
        },
        {
          "id": "anthropic-opus-think",
          "name": "Claude 4.5 Opus Thinking",
          "description": "Anthropic's previous advanced LLM with thinking",
          "pro": false,
          "max": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "google",
      "models": [
        {
          "id": "gemini-3-flash",
          "name": "Gemini 3 Flash",
          "description": "Google's latest small SOTA LLM",
          "pro": true,
          "max": false,
          "new": true,
        },
        {
          "id": "gemini-3-flash-think",
          "name": "Gemini 3 Flash Thinking",
          "description": "Google's latest small SOTA LLM with thinking",
          "pro": true,
          "max": false,
          "new": true,
        },
        {
          "id": "gemini-3.1-flash-lite",
          "name": "Gemini 3.1 Flash Lite",
          "description": "Google's newest lightweight flash LLM",
          "pro": false,
          "max": false,
          "new": true,
        },
        {
          "id": "gemini-3.1-flash-lite-think",
          "name": "Gemini 3.1 Flash Lite Thinking",
          "description": "Google's newest lightweight flash LLM with thinking",
          "pro": true,
          "max": false,
          "new": true,
        },
        {
          "id": "gemini-3.1-pro",
          "name": "Gemini 3.1 Pro",
          "description": "Google's newest SOTA LLM",
          "pro": false,
          "max": true,
          "new": true,
        },
        {
          "id": "google-lite",
          "name": "Gemini 2.5 Flash Lite",
          "description": "Google's advanced small LLM",
          "pro": false,
          "max": false,
          "new": false,
        },
        {
          "id": "google",
          "name": "Gemini 2.5 Flash",
          "description": "Google's advanced small LLM",
          "pro": true,
          "max": false,
          "new": false,
        },
        {
          "id": "google-think",
          "name": "Gemini 2.5 Flash Thinking",
          "description": "Google's advanced small LLM with thinking",
          "pro": true,
          "max": false,
          "new": false,
        },
        {
          "id": "google-pro",
          "name": "Gemini 2.5 Pro",
          "description": "Google's advanced LLM",
          "pro": true,
          "max": false,
          "new": false,
        },
        {
          "id": "google-pro-think",
          "name": "Gemini 2.5 Pro Thinking",
          "description": "Google's advanced LLM with thinking",
          "pro": true,
          "max": false,
          "new": false,
        },
      ],
    },
    {
      "provider": "xai",
      "models": [
        {
          "id": "grok-4.20-multi-agent-beta-latest",
          "name": "Grok 4.20 Multi Agent Beta",
          "description": "xAI's experimental beta multi-agent model",
          "pro": true,
          "new": true,
        },
        {
          "id": "grok-4.20-experimental-beta-0304",
          "name": "Grok 4.20 Beta",
          "description": "xAI's experimental beta chat model",
          "pro": true,
          "new": true,
        },
        {
          "id": "grok-4.20-experimental-beta-0304-thinking",
          "name": "Grok 4.20 Beta Thinking",
          "description": "xAI's experimental beta reasoning model",
          "pro": true,
          "new": true,
        },
        {
          "id": "default",
          "name": "Grok 4.1 Fast",
          "description": "xAI's greatest and fastest multimodel LLM",
          "pro": false,
          "new": true,
          "default": true,
        },
        {
          "id": "grok4.1-fast-thinking",
          "name": "Grok 4.1 Fast Thinking",
          "description": "xAI's greatest and fastest multimodel reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "grok-3-mini",
          "name": "Grok 3 Mini",
          "description": "xAI's recent smallest LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "grok-3",
          "name": "Grok 3",
          "description": "xAI's recent smartest LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "grok-4",
          "name": "Grok 4",
          "description": "xAI's most intelligent LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "grok-4-fast",
          "name": "Grok 4 Fast",
          "description": "xAI's previous fastest multimodel LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "grok-4-fast-think",
          "name": "Grok 4 Fast Thinking",
          "description": "xAI's previous fastest multimodel reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "code",
          "name": "Grok Code",
          "description": "xAI's advanced coding LLM",
          "pro": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "deepseek",
      "models": [
        {
          "id": "deepseek-chat",
          "name": "DeepSeek v3.2",
          "description": "DeepSeek's advanced chat LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "deepseek-chat-think",
          "name": "DeepSeek v3.2 Thinking",
          "description": "DeepSeek's advanced chat LLM with thinking",
          "pro": true,
          "new": true,
        },
        {
          "id": "deepseek-v3",
          "name": "DeepSeek v3",
          "description": "DeepSeek's previous advanced chat LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "deepseek-v3.1-terminus",
          "name": "DeepSeek v3.1 Terminus",
          "description": "DeepSeek's advanced chat LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "deepseek-chat-exp",
          "name": "DeepSeek v3.2 Exp",
          "description": "DeepSeek's advanced chat LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "deepseek-chat-think-exp",
          "name": "DeepSeek v3.2 Exp Thinking",
          "description": "DeepSeek's advanced chat LLM with thinking",
          "pro": true,
          "new": false,
        },
        {
          "id": "deepseek-r1",
          "name": "DeepSeek R1",
          "description": "DeepSeek's advanced reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "deepseek-r1-0528",
          "name": "DeepSeek R1 0528",
          "description": "DeepSeek's advanced reasoning LLM",
          "pro": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "alibaba",
      "models": [
        {
          "id": "qwen-3.5",
          "name": "Qwen 3.5 397B A17B",
          "description": "Alibaba's latest flagship LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-3.5-plus",
          "name": "Qwen 3.5 Plus",
          "description":
              "Alibaba's latest flagship LLM with vision and reasoning",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-3.5-27b",
          "name": "Qwen 3.5 27B",
          "description": "Alibaba's Qwen 3.5 27B vision reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-3.5-35b",
          "name": "Qwen 3.5 35B A3B",
          "description": "Alibaba's Qwen 3.5 35B A3B vision reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-3.5-122b",
          "name": "Qwen 3.5 122B A10B",
          "description": "Alibaba's Qwen 3.5 122B A10B vision reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-3.5-flash",
          "name": "Qwen 3.5 Flash",
          "description": "Alibaba's fast vision reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-coder-next",
          "name": "Qwen 3 Coder Next",
          "description": "Alibaba's next-gen coding LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-3-max-preview-thinking",
          "name": "Qwen 3 Max Thinking",
          "description": "Qwen's most advanced reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "qwen-32b",
          "name": "Qwen 3 32B",
          "description": "Alibaba's base LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "qwen-32b-thinking",
          "name": "Qwen 3 32B Thinking",
          "description": "Alibaba's base reasoning LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "qwen-4b",
          "name": "Qwen 3 4B",
          "description": "Alibaba's small base LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "qwen-4b-thinking",
          "name": "Qwen 3 4B Thinking",
          "description": "Alibaba's small base LLM",
          "pro": false,
          "new": false,
        },
        {
          "id": "qwen-coder-small",
          "name": "Qwen 3 Coder 30B A3B Instruct",
          "description": "Alibaba's advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-coder",
          "name": "Qwen 3 Coder",
          "description": "Alibaba's advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-coder-plus",
          "name": "Qwen 3 Coder Plus",
          "description": "Alibaba's extremely advanced coding LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-vl-30b",
          "name": "Qwen 3 VL 30B",
          "description": "Alibaba's advanced vision LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-vl-30b-thinking",
          "name": "Qwen 3 VL 30B Thinking",
          "description": "Alibaba's advanced vision LLM with thinking",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-next",
          "name": "Qwen 3 Next 80B A3B Instruct",
          "description": "Qwen's advanced instruct LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-next-think",
          "name": "Qwen 3 Next 80B A3B Thinking",
          "description": "Qwen's advanced thinking LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-max",
          "name": "Qwen 3 Max",
          "description": "Qwen's advanced instruct LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-max-preview",
          "name": "Qwen 3 Max Preview",
          "description": "Qwen's advanced instruct LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-235",
          "name": "Qwen 3 235B A22B",
          "description": "Qwen's advanced instruct LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-235-think",
          "name": "Qwen 3 235B A22B Thinking",
          "description": "Qwen's advanced thinking LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-vl",
          "name": "Qwen 3 VL",
          "description": "Qwen's advanced vision LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "qwen-3-vl-thinking",
          "name": "Qwen 3 VL Thinking",
          "description": "Qwen's advanced vision LLM with thinking",
          "pro": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "minimax",
      "models": [
        {
          "id": "minimax-m2.7",
          "name": "MiniMax M2.7",
          "description": "MiniMax's latest high-speed reasoning LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "minimax",
          "name": "Minimax M1 80K",
          "description": "Minimax's advanced reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "minimax-m2",
          "name": "Minimax M2",
          "description": "Minimax's advanced reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "minimax-m2.1",
          "name": "Minimax M2.1",
          "description": "Minimax's latest advanced reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "minimax-m2.1-lightning",
          "name": "Minimax M2.1 Lightning",
          "description": "Minimax's fast advanced reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "minimax-m2.5",
          "name": "Minimax M2.5",
          "description": "Minimax's most capable reasoning LLM",
          "pro": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "mistral",
      "models": [
        {
          "id": "ministral-3b",
          "name": "Ministral 3 3B",
          "description": "Mistral's mini-model 3B multi-modal LLM",
          "pro": false,
          "new": true,
        },
        {
          "id": "ministral-8b",
          "name": "Ministral 3 8B",
          "description": "Mistral's mini-model 8B multi-modal LLM",
          "pro": false,
          "new": true,
        },
        {
          "id": "devstral",
          "name": "Devstral 2",
          "description": "Mistral's coding-focused LLM",
          "pro": false,
          "new": true,
        },
        {
          "id": "devstral-small",
          "name": "Devstral Small 2",
          "description": "Mistral's small coding-focused LLM",
          "pro": false,
          "new": true,
        },
        {
          "id": "ministral-14b",
          "name": "Ministral 3 14B",
          "description": "Mistral's mini-model 14B multi-modal LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "mistral-large",
          "name": "Mistral Large 3",
          "description": "Mistral's latest and greatest large multi-modal LLM",
          "pro": true,
          "new": true,
        },
        {
          "id": "mistral-small",
          "name": "Mistral Small 4",
          "description": "Mistral's small efficient model",
          "pro": false,
          "new": true,
        },
        {
          "id": "mistral-small-think",
          "name": "Mistral Small 4 Thinking",
          "description": "Mistral's small model with reasoning mode enabled",
          "pro": false,
          "new": true,
        },
        {
          "id": "leanstral",
          "name": "Leanstral",
          "description": "Mistral's lean and efficient small model",
          "pro": false,
          "new": true,
        },
        {
          "id": "mistral-medium",
          "name": "Mistral Medium",
          "description": "Mistral's medium multi-modal LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "magistral-small",
          "name": "Magistral Small",
          "description": "Mistral's small reasoning LLM",
          "pro": true,
          "new": false,
        },
        {
          "id": "magistral-medium",
          "name": "Magistral Medium",
          "description": "Mistral's medium reasoning LLM",
          "pro": true,
          "new": false,
        },
      ],
    },
    {
      "provider": "sarvam",
      "models": [
        {
          "id": "sarvam-105b",
          "name": "Sarvam 105B",
          "description": "Sarvam's flagship model for chat and reasoning",
          "pro": true,
          "new": true,
        },
      ],
    },
  ],
};
